# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-25 21:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobinformation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('pup_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.RenameModel(
            old_name='InformationType',
            new_name='ItemType',
        ),
        migrations.RemoveField(
            model_name='textinformation',
            name='infotype',
        ),
        migrations.RenameField(
            model_name='itemtype',
            old_name='type_text',
            new_name='item',
        ),
        migrations.DeleteModel(
            name='TextInformation',
        ),
        migrations.AddField(
            model_name='note',
            name='itemType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobinformation.ItemType'),
        ),
    ]
