# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-25 21:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobinformation', '0002_auto_20160425_1635'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='note',
            table='note',
        ),
    ]
