# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-25 21:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobinformation', '0003_auto_20160425_1647'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='itemtype',
            table='item_type',
        ),
    ]
