# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-25 22:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobinformation', '0004_auto_20160425_1649'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemType',
            new_name='Topic',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='itemType',
            new_name='topic',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='item',
            new_name='topic',
        ),
        migrations.AlterModelTable(
            name='topic',
            table='topic',
        ),
    ]
